return {
	require("plugins.themes.ayu"),
	require("plugins.themes.catppuccin"),
	require("plugins.themes.dracula"),
	require("plugins.themes.everforest"),
	require("plugins.themes.github-theme"),
	require("plugins.themes.gruvbox"),
	require("plugins.themes.kanagawa"),
	require("plugins.themes.monokai-pro"),
	require("plugins.themes.nightfox"),
	require("plugins.themes.nord"),
	require("plugins.themes.onedark"),
	require("plugins.themes.oxocarbon"),
	require("plugins.themes.rose-pine"),
	require("plugins.themes.sonokai"),
	require("plugins.themes.tokyonight"),
}
